---
# defaults file for invoke_build---
# Git source code URL
repository:

# build detination
build_destination: /usr/apps/release_tag

# folder for binary
build_bin_fold: /usr/apps/release_tag

# build_script
build_script: '/usr/apps/release_tag/build &> /usr/apps/release_tag/build_result.txt'

